apiVersion: v1
kind: Service
metadata:
  name: projet-service-cloud-service
spec:
  type: LoadBalancer
  ports:
    - port: 80        
      targetPort: 8080    
  selector:
    app: projet-service-cloud

